version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
clone_folder: C:\workspace

image:
    - Visual Studio 2015
    - Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
    - git config --global core.autocrlf input
    - if "%PLATFORM%"=="x64" ( set arch= Win64)
    - echo %arch%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
    - echo %generator%

install:

environment:
    APPVEYOR_RDP_PASSWORD: password

   
#---------------------------------#
#       build configuration       #
#---------------------------------#
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
    #- x86
    - x64

# to add several configurations to build matrix:
configuration:
    #- Debug
    - Release

build:
    parallel: true                  # enable MSBuild parallel builds
    # MSBuild verbosity level
    verbosity: quiet|minimal|normal|detailed

build_script:
    # Build the library
    - cd c:\workspace
    - md build
    - cd build
    - cmake -DBUILD_TESTING:BOOL=ON -G %generator% ..
    - cmake --build . --config %CONFIGURATION%

after_build:

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
    - ctest -C %CONFIGURATION% -VV

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
#    - path: C:\workspace\build\%CONFIGURATION%\**
#      name: leetcode_package

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

on_finish:
    # Enable RDP
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))